name: 02-Workflow-event

on:
  #push:
  #  branches:
  #    - main
  pull_request:
  #schedule:
  #  - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I have been triggered by an ${{github.event_name}} event."
                        