name: 03-Workflow-runner

on:
  workflow_dispatch:

jobs:
  Ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is rinning on an Ubuntu runner."
          echo "Runner OS: $RUNNER_OS"
          
  Windows-echo:
    runs-on: Windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "This job is rinning on an Windows runner."
          echo "Runner OS: $RUNNER_OS"

  Mac-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on a Mac runner."
          echo "Runner OS: $RUNNER_OS"


