name: 04-using-action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: |
          pwd
          ls
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        working-directory: 04-using-action/react-app
        run: npm ci
       

    # 0. Checkout the code from the repository
    # 1. Install deps of react application 
    # 2. Execute automated tests




