name: 03-Workflow-runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls

    # 0. Checkout the code from the repository
    # 1. Install deps of react application 
    # 2. Execute automated tests




