name: 05-Event_Filter and Activity_Types

on:
  pull_request:
    types:
        - opened
        - synchronize
    branches:
        - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a PR is opened or synchrinized and base branch is main"
                        