name: 06-Event_Filter and Activity_Types
run-name: 06-Event_Filter and Activity_Types | Debug - ${{inputs.debug}}

on:
   #push:
   #  branches:
   #     - main
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

env:
    My_Workflow_Var: 'workflow'
    My_Overwrittern_Var: 'workflow'
jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            My_Job_Var: 'job'
            My_Overwrittern_Var: 'job'
        steps:
            - name: Display information
              run: |
                echo "Event Name: ${{github.event_name}}"
                echo "Ref: ${{github.ref}}"
                echo "SHA: ${{github.sha}}"
                echo "Actor: ${{github.actor}}"
                echo "Workflow: ${{github.workflow}}"
                echo "Run ID: ${{github.run_id}}"
                echo "Run number: ${{github.run_number}}"

            - name: Retrieve Variable
              run: |
                echo "Variable value: ${{vars.My_VAR}}"

            - name: print Env Variable
              env:
                My_Overwrittern_Var: 'step'   
              run: |
                echo "Workflow env: ${{env.My_Workflow_Var}}"
                echo "Overwriten env: ${{env.My_Overwrittern_Var}}"

            - name: print Env Variable
              run: |
                echo "Workflow env: ${{env.My_Workflow_Var}}"
                echo "Overwriten env: ${{env.My_Overwrittern_Var}}"

