name: 08-Using Variables.

on:
    #push:
    #  branches:
    #    - main
    workflow_dispatch:

env:
  WORKFLOW_VAR: "I am a workflow env var"
  OVERWRITTEN: "Overwritten workflow"
jobs:
    echo:
        runs-on: ubuntu-latest
        env:
          JOB_VAR: "I am a job env var"
          OVERWRITTEN: "Overwritten Job"
        steps:
            - name: "Print Env Variables"
              env:
                STEP_VAR: "I am a step env var"
              run: |
                echo "Step env var ${{env.STEP_VAR}}"
                echo "Job env var ${{env.JOB_VAR}}"
                echo "workflow env var ${{env.WORKFLOW_VAR}}"
                echo "Overwritten env var ${{env.OVERWRITTEN}}"
            
            - name: "Print Env Variables"
              env:
                OVERWRITTEN: "Overwritten Step"
              run: |
                echo "Overwritten env var ${{env.OVERWRITTEN}}"    

              