name: 10-Execution-flow.

on:
    workflow_dispatch:
        inputs:
            pass-unit-test:
                type: boolean
                description: Whether unit test will pass or not
                default: true

jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: "Lint and Build"
              run: echo "Linting and Building project"
    unit-test:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: "Running unit tests"
              run: echo "Running tests..."
            - name: "Failing tests"
              if: ${{ !inputs.pass-unit-test}}
              run: exit 1        
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs:
            - lint-build
            - unit-test
        steps:
            - name: "Deploying to non-prod"
              run: echo "Deploying to non prod.... ^_^"
    e2e-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod       
        steps:
            - name: "Running e2e tests"
              run: echo "Running e2e tests...."
    load-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod 
        steps:
            - name: "Running load tests"
              run: echo "Running load tests...."        
    deployment:
        runs-on: ubuntu-latest
        needs:
            - load-tests
            - e2e-tests 
        steps:
            - name: "Deploying to prod"
              run: echo "Deploying to Prod ..... :)"
