name: 11-imputs.

on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: Skip the deployment 
                default: true
            target:
                type: environment
                required: true
                description: Which environment workflow will target
            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
                            
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Build"
              run: echo "Building project from tag ${{inputs.tag}}"
    deploy:
        runs-on: ubuntu-latest
        if: ${{ !inputs.dry-run}}
        environment: ${{inputs.target}}
        steps:
            - name: "Deploy"
              run: echo "Deploying to ${{inputs.target}}"