name: 18.1 - Reusable-workflow

on:
  workflow_call:
    inputs:
        target-dir:
            type: string
            required: true
    outputs:
        build-status:
            description: The status of the build process
            value: ${{jobs.deploy.outputs.build-status}}
        url:
            description: The url of the deployed version
            value: ${{jobs.deploy.outputs.url}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
        build-status: ${{steps.build.outputs.build-status}}
        url: ${{steps.deploy.outputs.url}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
            echo "Build using directory ${{inputs.target-dir}}"
            echo "build-status" >> "$GITHUB_OUTPUT"

      - name: Deploy
        id: deploy
        run: |
            echo "Deploying build artifacts..."
            echo "url=https://www.google.com" >> "$GITHUB_OUTPUT"