name: 18.2 - Reusable-workflows

on:
  workflow_dispatch:

jobs:
  somejob:
    uses: ./.github/workflows/18.2-reusable-workflow-test.yaml
    with:
        target-directory: dummy-dir

  print-output:
    runs-on: ubuntu-latest
    needs: somejob
    steps:
        - name: Print outputs
          run: |
            echo "Build status: ${{needs.deploy.build-status}}"
            echo "URL: ${{needs.deploy.url}}" 