name: Parallel Execution Workflow

on:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application
        run: echo "Building the project..."
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]  # Runs in parallel for each version
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Tests
        run: echo "Running tests on Node.js ${{ matrix.node-version }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Waits for build & test jobs to finish
    steps:
      - name: Deploy Application
        run: echo "Deploying application..."
